services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: resiliencia-api
    ports:
      - "5050:8080"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: resiliencia-frontend
    ports:
      - "8080:80"
    depends_on:
      - api
